dynamic_title = true
opacity = 1
startup_mode = "Windowed"

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window.dimensions]
columns = 120
lines = 40
