format = """
[░▒▓](#a3aed2)\
[  $username](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
$all\
\n$character"""

[cmd_duration]
min_time = 500
show_milliseconds = true

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = '[ $path ]($style)'
truncation_length = 2
truncation_symbol = "…/"

[directory.substitutions]
'Documents' = '󰈙 '
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_commit]
tag_symbol = '  '

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[c]
symbol = " "

[dart]
symbol = " "

[lua]
symbol = " "

[python]
symbol = " "

[nodejs]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = "󱘗 "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[line_break]
disabled = false

[username]
style_user = "bg:#a3aed2 fg:#090c0c"
format = "[$user]($style)"
disabled = false
show_always = true

[kubernetes]
disabled = false
format = '$symbol[$context/$namespace]($style) '
style = 'bold blue'

[[kubernetes.contexts]]
context_pattern = "gke_.*_(?P<var_cluster>[\\w-]+)"
context_alias = "gke-$var_cluster"

[[kubernetes.contexts]]
context_pattern = "arn:aws:eks:us-west-2:(?P<account_id>\\d+):cluster/(?P<cluster>.+)"
context_alias = "$account_id:$cluster"

[gcloud]
disabled = true
symbol = ''
format = 'on $symbol [\($project\)]($style) '

[aws]
disabled = true
format = '$symbol[$profile@$region]($style) '
style = 'bold blue'
symbol = ' '

[aws.profile_aliases]
default = 'default'

[aws.region_aliases]
us-west-2 = 'usw2'

[direnv]
disabled = false
format = '$symbol[$loaded/$allowed]($style) '
style = 'bold blue'
symbol = ' '

[terraform]
disabled = false
format = '$symbol[$version]($style) '
style = 'bold blue'
symbol = ' '
